sudo: required
language: java
jdk: oraclejdk8

services:
- docker

env:
  global:
  - secure: "GvxdH0sk/oL6kPexb4op7GEHmzXcUoLcEKMU6jS9qPny3vaoLxUTf7d5TgH/X++UeDrM2Zc0u6tc9AwUooYqJxt+U0VPAMbEdKoTo+/37mLD0gvLc6tB3wVv3qYJqzT0JNjAPYcvePm3HGcmm/HXo56aYBG7FFeHADd/otyFZ+hKq34fZV5DQpAeCQR3wrAJfgQjVCyUKAcUzEdMrdFZBLfbk0A2xXAp3DfgLpbTIoByyo/M+tuUVXqGuVhP2S5Sdy2I9Kf+Y52jJgPFBIhBlQdApJ0Ons1lfwjBrER+3sI9vZYDCR3m6kBgm7buKN7pY8c8fFIqEd7V1UH0PBF8BMeICkqz7CBSEc1+fh/1GOcZA5pCXoTChmphaYAHOoOm4mSiH3p/K6kRyIfa4+XP0e1bT7oOm+RWjV/v4ogaxDMBgkGjskQeeLmeO+63gKXm5naaeVxDJhrMU5AkFSvCYR0GYNkNy8LtgskBNAUI73bKSW2oVBaGRDuCz4LcUxUtF76gnPpL3Qp+wF8+XYVecvcq/26OxC0fkr+e3wSRfP8Zv3Ue+Rq1tA+YH8OrdUmgVyGM/rdO9XHhvXcbW96d0irRV+UxwdEy9jaesp851wipZCi6XkSnOryaFJIHktnB3IRBVSH4E+4QLTdcjHkphEnbe6+qUE4LvPGvEpLUSK4="
  - secure: "c53j/rl/P8UQJ6gg/6eikSfVx8V3djo/8sxi3d0oIDbqV6vUYqvZvHSgc1HAAdQ+sxL1zER9JFB/GvaPE6I4uQFEpGzOvpkwdQO9iBJYIwlEd0ne/sg0fV2emrq4u1vqba8Mb2BnkgFiNtzE06Q14zLOywcfeRWaKHGGqmBPvOQljPuLMYL0RzqQIE3CSfaip8B2+IzVybf5b1h6S+opOWyq49qh24GtEZ1PuZ+Bv612dUYCU6BUpNDCmevjFXq82ilg9zkXSt6VbkCpvk5DJ1Ms+N2II8w4A7fPHk0dOmpDNtff/G5MtSReiq4HOP3BTCgDmhOZTyWfWlr6xEMoWmq6f/KN7/f6e4tcF7gRIczH3XQL+rm7cNSxc0W++vfiraQKM2h5KR+EEekxZKgPnheyqH8dBxSMu8YCXwJATzPUC5h9q4ATCoOUKPQvfEKaUL/UaySIU3dv+2kmN+8Lid4WaNSjZSn2Qk19ym39n6mQvzgPAprybhuGd4uKbHb7jsQiZ5rbcuOsn1FadBRRluIxU2XiapfQlSRIqw0S2U58XieQK5XkEMOh15Zs28TK6sK7sHctwstaKACXKtfWpP0ahU3GPRmfSPbQWQZtWTkir0kUwm7VnrSR9Gz4X7gsg9K76D328poXkrsxda1on16CSsU5q5DCg5sThMEqcVw="
  - secure: "Z6xgFh4BGvJsQCqDDSKs9uD2o8Bqu1OBwPLgkW8X/ueOO+ca6nfczasZMbq06GZ8BLWnYAZrjVzcgIPNpxBI+OwGkgJZSgqCot7zeIKIMiWMXiF9hc2f2GLgAGcRHI4LWKCFLp9tlLB7+xj/B1WhjPlMfzk8r0WPdl2dAQeDtdFzGwAh4kpxZKlfBO+H5YdTrkq8L4tIVyuHVjPWOnMYVNq4nnLE7DTEkrh1MKQk9/H0xXJ4UCYBhjnjKuB5VwaP6vkifLzP7a/pETYEvO0k/EB9VzWWBQ26Ft4VrbJT/03dSI2r9F+E4aibfZXEazGoEYm4FLPkDZwHIZQTPkvGKFXs2Kx82k5eyLqgmU8KAZhPujiNAq9grOFYgoCT+FrnQyzU0AChxdySMP9JQQnPLuUqPE3dCnstLSQ4poyK3TJQNxcUddXsgrQpySeH8VGkGKyv74PUJHdxOESAhqQIuoeRxJaj1cPileZqxVLwxwJXF284ZZSAt/ZLMZRgQRveV5bEyOiFGevpppSsVFxY4AjnIBsHahzuybpSpXaOtNxNzZ51sWj95vF1Ovnr6/LJbztDRwycxF5jNbr0vAuMKDWQqVznt9tgoHpyv7MLcfYbjOU30vqmuc9th6PfmJ3nnr0RHpEpn8aSwYJI9thNaaSzoiHUTN745+bF7voaRpE="
  - secure: "OLHberYOPZ39lxVDqa0lvuqrVyGkEn+YjRuuUdfPRxxoujgWhZrjX2sCmBCx+wP5d9Wa/NCAFHe0fqNROM+2YchD7Usz5E7D85HVV5GsvXi2quKM8VDAJVrni+QIIpOm4tojZNOY0sZMuxS4r2h2P/W1lz+NZGQXYxEtp5CkHPInHYEGOoqpMvLOoJONxZ3erlQQcSq0CM6W7bpj0ucRtXHpZZ8QUnJNhRu2aA3ddmH7ULegrAedElMzfNjfMMNxIbD7yvwXbvODy6gavakpRBbfKp9i3D/SaZ5HrRiQBdQCUzrDpcJTWUme8CR8IQSeq+jNG+l9s2e08t79dLx3nDPcjERInPtevf12NP/thriBM8c5r/s+EGqmNGQOIkmm+wn8h59QtQnRopgFW86q4R+ralods5rUoOz0im1250AqlwvjLfjTsTtdRYA8GE8trpvEM2n1SIePWNwEbTWYVsxCP9tVPbE04O9E7Qreombds9wnZGD/REMsJLg4vS7u3eZAMa7IB05aGdkXMf5OzG2JI6q0mL1DzSPUNPEqa8tLaes+mdOWgJY7IOGpBmQz84X9JIcA0mp1KRz3hHcqyKVeNRVJTquiCNDX1hnoELdmYBdQN3474KXN8bVuymhjo9GYsEn8zc0VXn0m/Z8kDKlu55NodhQILvEJGQqKTD8="
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "im-mr-kotte-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
- export IMAGE_NAME=bhanu11220teja/springtest
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: mr-kotte-spring-test