sudo: required
language: java
jdk: oraclejdk8

services:
- docker

env:
  global:
  - secure: "Y5CtndUM0yY96yBhHhrX9aueI+9D9MaScT4n2wQdpT48k1FTHeGyhh0LWGWdb/pCBVEuo6tmt7awzCgS39GAS8a9A/9mktSHBliDWopr0OQop2vncd26C/qeR51HWzUge20TeAowtILKdSDyx7/JfV4N1g29pYKjHj71lXCF7N8BFN00wihlDD1OCslrAEGHEpsA+EUtnGOQctZs909vpOz5ZJy9qOlarwp859XQ5u+qsqsiPhtr86P/z1exWq8vAl2wHeg9jbxla0VoWSDhiDpCdnZKDLhOWboVcIaO+raQTHi8l53wpt+t0WVfFWQrItPvmbkkjo+gAMFn538NJkJgOuOyy9ebHwxXzEjc43gyybJqsF9XbyUptwHubCUPIWkbKpcjlgiFz0mdYKpQcA7Ad5ULqoNlQSu9WDf20G4mJy8z6VuY1zKBV2PCCzmu6f4hsAh6BNxS618QdS8/yZTggqgVEsWMyqbTxSg/Q1hViYgoEyQ0InMk8+cWmbKwEpmsKHwkeybraGHw6zRbFEKT+Vesu93bj/+0A2Jk7yha8yni6CLErRCJgFMlgCwJnAC//ddDJFJpVlhPW4zdbOW0iIcaCLKhKNdIKXtrTuCGJ5NitoHRuBeXzbf+YzvSAR2TTynBpri1hXs6zJSpHh9LSWTAqxj53hcm7aA1uzc="
  - secure: "c53j/rl/P8UQJ6gg/6eikSfVx8V3djo/8sxi3d0oIDbqV6vUYqvZvHSgc1HAAdQ+sxL1zER9JFB/GvaPE6I4uQFEpGzOvpkwdQO9iBJYIwlEd0ne/sg0fV2emrq4u1vqba8Mb2BnkgFiNtzE06Q14zLOywcfeRWaKHGGqmBPvOQljPuLMYL0RzqQIE3CSfaip8B2+IzVybf5b1h6S+opOWyq49qh24GtEZ1PuZ+Bv612dUYCU6BUpNDCmevjFXq82ilg9zkXSt6VbkCpvk5DJ1Ms+N2II8w4A7fPHk0dOmpDNtff/G5MtSReiq4HOP3BTCgDmhOZTyWfWlr6xEMoWmq6f/KN7/f6e4tcF7gRIczH3XQL+rm7cNSxc0W++vfiraQKM2h5KR+EEekxZKgPnheyqH8dBxSMu8YCXwJATzPUC5h9q4ATCoOUKPQvfEKaUL/UaySIU3dv+2kmN+8Lid4WaNSjZSn2Qk19ym39n6mQvzgPAprybhuGd4uKbHb7jsQiZ5rbcuOsn1FadBRRluIxU2XiapfQlSRIqw0S2U58XieQK5XkEMOh15Zs28TK6sK7sHctwstaKACXKtfWpP0ahU3GPRmfSPbQWQZtWTkir0kUwm7VnrSR9Gz4X7gsg9K76D328poXkrsxda1on16CSsU5q5DCg5sThMEqcVw="
  - secure: "Z6xgFh4BGvJsQCqDDSKs9uD2o8Bqu1OBwPLgkW8X/ueOO+ca6nfczasZMbq06GZ8BLWnYAZrjVzcgIPNpxBI+OwGkgJZSgqCot7zeIKIMiWMXiF9hc2f2GLgAGcRHI4LWKCFLp9tlLB7+xj/B1WhjPlMfzk8r0WPdl2dAQeDtdFzGwAh4kpxZKlfBO+H5YdTrkq8L4tIVyuHVjPWOnMYVNq4nnLE7DTEkrh1MKQk9/H0xXJ4UCYBhjnjKuB5VwaP6vkifLzP7a/pETYEvO0k/EB9VzWWBQ26Ft4VrbJT/03dSI2r9F+E4aibfZXEazGoEYm4FLPkDZwHIZQTPkvGKFXs2Kx82k5eyLqgmU8KAZhPujiNAq9grOFYgoCT+FrnQyzU0AChxdySMP9JQQnPLuUqPE3dCnstLSQ4poyK3TJQNxcUddXsgrQpySeH8VGkGKyv74PUJHdxOESAhqQIuoeRxJaj1cPileZqxVLwxwJXF284ZZSAt/ZLMZRgQRveV5bEyOiFGevpppSsVFxY4AjnIBsHahzuybpSpXaOtNxNzZ51sWj95vF1Ovnr6/LJbztDRwycxF5jNbr0vAuMKDWQqVznt9tgoHpyv7MLcfYbjOU30vqmuc9th6PfmJ3nnr0RHpEpn8aSwYJI9thNaaSzoiHUTN745+bF7voaRpE="
  - secure: "OLHberYOPZ39lxVDqa0lvuqrVyGkEn+YjRuuUdfPRxxoujgWhZrjX2sCmBCx+wP5d9Wa/NCAFHe0fqNROM+2YchD7Usz5E7D85HVV5GsvXi2quKM8VDAJVrni+QIIpOm4tojZNOY0sZMuxS4r2h2P/W1lz+NZGQXYxEtp5CkHPInHYEGOoqpMvLOoJONxZ3erlQQcSq0CM6W7bpj0ucRtXHpZZ8QUnJNhRu2aA3ddmH7ULegrAedElMzfNjfMMNxIbD7yvwXbvODy6gavakpRBbfKp9i3D/SaZ5HrRiQBdQCUzrDpcJTWUme8CR8IQSeq+jNG+l9s2e08t79dLx3nDPcjERInPtevf12NP/thriBM8c5r/s+EGqmNGQOIkmm+wn8h59QtQnRopgFW86q4R+ralods5rUoOz0im1250AqlwvjLfjTsTtdRYA8GE8trpvEM2n1SIePWNwEbTWYVsxCP9tVPbE04O9E7Qreombds9wnZGD/REMsJLg4vS7u3eZAMa7IB05aGdkXMf5OzG2JI6q0mL1DzSPUNPEqa8tLaes+mdOWgJY7IOGpBmQz84X9JIcA0mp1KRz3hHcqyKVeNRVJTquiCNDX1hnoELdmYBdQN3474KXN8bVuymhjo9GYsEn8zc0VXn0m/Z8kDKlu55NodhQILvEJGQqKTD8="
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "mr-kotte-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
- export IMAGE_NAME=mrkotte/springtest
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: mr-kotte-spring-test